# Generated by Django 4.2.27 on 2025-12-31 07:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Customer ID or reference number', max_length=100)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name (optional)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bill amount in PKR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee charged', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(help_text='Bill due date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', help_text='Current status of the bill', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date and time when bill was paid', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, help_text='Associated transaction when bill is paid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='transactions.transaction')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='bills_bill_custome_f73e08_idx'), models.Index(fields=['due_date'], name='bills_bill_due_dat_cfdde0_idx'), models.Index(fields=['status'], name='bills_bill_status_aaa1ed_idx'), models.Index(fields=['created_at'], name='bills_bill_created_41cbb7_idx')],
            },
        ),
    ]
