# Generated by Django 4.2.27 on 2026-01-02 17:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_bw_cost', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Cost per page for Black & White printing (PKR)', max_digits=10)),
                ('print_color_cost', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Cost per page for Color printing (PKR)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
