# Generated by Django 4.2.27 on 2025-12-30 17:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out')], help_text='Type of transaction: Cash In or Cash Out', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in PKR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee or profit from this transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('OTHER', 'Other')], default='CASH', help_text='Method of payment', max_length=20)),
                ('cash_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received (auto-calculated)', max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid out (auto-calculated)', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Additional notes or description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction was recorded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time')),
                ('created_by', models.ForeignKey(help_text='User who recorded this transaction', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='transaction_created_300c15_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['created_by'], name='transaction_created_9eff96_idx')],
            },
        ),
    ]
