# Generated by Django 4.2.27 on 2025-12-30 17:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_created_9eff96_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money received (auto-calculated)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_out',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money paid out (auto-calculated)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When transaction was recorded'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(help_text='Staff member who recorded this', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee or commission earned', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes or customer details'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BANK', 'Bank')], default='CASH', help_text='How the payment was made or received', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('JAZZCASH_SEND', 'JazzCash Send'), ('EASYPAISA_SEND', 'EasyPaisa Send'), ('BILL_PAYMENT', 'Bill Payment'), ('STATIONARY_SALE', 'Stationary Sale'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_WITHDRAWAL', 'Bank Withdrawal'), ('OTHER', 'Other')], help_text='Type of transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_mode'], name='transaction_payment_1baa30_idx'),
        ),
    ]
