# Generated by Django 4.2.27 on 2025-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_transaction_created_9eff96_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('JAZZCASH_SEND', 'JazzCash Send Money'), ('JAZZCASH_RECEIVE', 'JazzCash Receive/Credit'), ('EASYPAISA_SEND', 'EasyPaisa Send Money'), ('EASYPAISA_RECEIVE', 'EasyPaisa Receive/Credit'), ('BILL_PAYMENT', 'Bill Payment'), ('STATIONARY_SALE', 'Stationary Sale'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_WITHDRAWAL', 'Bank Withdrawal'), ('OTHER', 'Other')], help_text='Type of transaction', max_length=20),
        ),
    ]
