# Generated by Django 4.2.27 on 2025-12-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MOBILE_WALLET_SEND', 'JazzCash/EasyPaisa Send'), ('MOBILE_WALLET_RECEIVE', 'JazzCash/EasyPaisa Receive'), ('BILL_PAYMENT', 'Bill Payment'), ('STATIONARY_SALE', 'Stationary Sale'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_WITHDRAWAL', 'Bank Withdrawal'), ('OTHER', 'Other')], help_text='Type of transaction', max_length=30),
        ),
    ]
