# Generated by Django 4.2.27 on 2025-12-31 07:13

from django.db import migrations


def update_transaction_types(apps, schema_editor):
    """Convert old transaction types to new combined types."""
    Transaction = apps.get_model('transactions', 'Transaction')
    
    # Update all JazzCash and EasyPaisa send transactions
    Transaction.objects.filter(
        transaction_type__in=['JAZZCASH_SEND', 'EASYPAISA_SEND']
    ).update(transaction_type='MOBILE_WALLET_SEND')
    
    # Update all JazzCash and EasyPaisa receive transactions
    Transaction.objects.filter(
        transaction_type__in=['JAZZCASH_RECEIVE', 'EASYPAISA_RECEIVE']
    ).update(transaction_type='MOBILE_WALLET_RECEIVE')


def reverse_transaction_types(apps, schema_editor):
    """Reverse migration - convert back to JazzCash (default)."""
    Transaction = apps.get_model('transactions', 'Transaction')
    
    # Convert back to JazzCash as default
    Transaction.objects.filter(
        transaction_type='MOBILE_WALLET_SEND'
    ).update(transaction_type='JAZZCASH_SEND')
    
    Transaction.objects.filter(
        transaction_type='MOBILE_WALLET_RECEIVE'
    ).update(transaction_type='JAZZCASH_RECEIVE')


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RunPython(update_transaction_types, reverse_transaction_types),
    ]
