# Generated by Django 4.2.27 on 2025-12-31 08:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service fee or commission earned', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MOBILE_WALLET_SEND', 'JazzCash/EasyPaisa Send'), ('MOBILE_WALLET_RECEIVE', 'JazzCash/EasyPaisa Receive'), ('CASH_CREDIT', 'Cash Credit (Load Balance)'), ('STATIONARY_SALE', 'Stationary Sale'), ('OTHER', 'Other')], help_text='Type of transaction', max_length=30),
        ),
    ]
