# Generated by Django 4.2.27 on 2026-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='print_type',
            field=models.CharField(blank=True, choices=[('BLACK_WHITE', 'Black & White'), ('COLOR', 'Color')], help_text='Print type for Print/Copy transactions', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('JAZZCASH_SEND', 'JazzCash Send'), ('JAZZCASH_RECEIVE', 'JazzCash Receive'), ('EASYPAISA_SEND', 'EasyPaisa Send'), ('EASYPAISA_RECEIVE', 'EasyPaisa Receive'), ('STATIONARY_SALE', 'Stationary Sale'), ('PRINT_COPY', 'Print/Copy'), ('DEPOSIT', 'Deposit'), ('CREDIT', 'Credit'), ('LOAD_PACKAGE', 'Load/Package'), ('OTHER', 'Other'), ('MOBILE_WALLET_SEND', 'Mobile Wallet Send (Old)'), ('MOBILE_WALLET_RECEIVE', 'Mobile Wallet Receive (Old)'), ('CASH_CREDIT', 'Cash Credit (Old)'), ('BILL_PAYMENT', 'Bill Payment'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_WITHDRAWAL', 'Bank Withdrawal')], help_text='Type of transaction', max_length=30),
        ),
    ]
