# Generated by Django 4.2.27 on 2026-01-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_print_type_and_more'),
    ]

    operations = [
    ]
