# Generated by Django 4.2.27 on 2026-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_add_new_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of pages/copies for Print/Copy transactions', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MOBILE_WALLET_SEND', 'JazzCash/EasyPaisa Send'), ('MOBILE_WALLET_RECEIVE', 'JazzCash/EasyPaisa Receive'), ('STATIONARY_SALE', 'Stationary Sale'), ('PRINT_COPY', 'Print/Copy'), ('DEPOSIT', 'Deposit'), ('CREDIT', 'Credit'), ('LOAD_PACKAGE', 'Load/Package'), ('OTHER', 'Other'), ('JAZZCASH_SEND', 'JazzCash Send (Old)'), ('JAZZCASH_RECEIVE', 'JazzCash Receive (Old)'), ('EASYPAISA_SEND', 'EasyPaisa Send (Old)'), ('EASYPAISA_RECEIVE', 'EasyPaisa Receive (Old)'), ('CASH_CREDIT', 'Cash Credit (Old)'), ('BILL_PAYMENT', 'Bill Payment'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_WITHDRAWAL', 'Bank Withdrawal')], help_text='Type of transaction', max_length=30),
        ),
    ]
