# Generated by Django 4.2.27 on 2026-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='print_type',
            field=models.CharField(blank=True, choices=[('BLACK_WHITE', 'Black & White'), ('COLOR', 'Color')], default='BLACK_WHITE', help_text='Print type for Print/Copy transactions', max_length=20, null=True),
        ),
    ]
